### ISSUE TITLE
AttributeError: The layer has never been called and thus has no defined input shape

### ISSUE THREAD

**Issue by youqun** [InES-HPMM/k2arm#1]
File "./main.py", line 93, in <module>
    numberOfDenseLayers = len(k2arm.getDenseLayersInformation(mc.model))
  File "d:\github\k2arm\host\Keras2arm.py", line 305, in getDenseLayersInformation
    Dense(layer.output_shape[1], name=layer.name))
  File "c:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1176, in output_shape
    raise AttributeError('The layer has never been called '
AttributeError: The layer has never been called and thus has no defined output shape.

**Comment by rarazac** [comment]
Which tensorflow version do you use?

**Comment by youqun** [comment]
Python 3.6.5 |Anaconda, &  tensorflow-1.3.0rc0-cp36-cp36m-win_amd64.whl
Tks.

**Comment by rarazac** [comment]
Can you verify the versions as shown in image below:

![versions](https://user-images.githubusercontent.com/24594953/54016985-f0072780-4184-11e9-9bde-43943b8041a1.png)

Thank you!

**Comment by rarazac** [comment]
Closed due to inactivity
