### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by PriceWang** [InES-HPMM/k2arm#2]
HI,

I'm trying to use k2arm.py to conver my own model/weights from keras to C header but get error "TypeError: 'NoneType' object is not callable". It happens when I call function "findOutputFormat" -> "buildNewModel" -> "nextLayer = self.getLayer(layer)(layerBefore)". Seems it return a nonetype object. Can you explan the algrithom and give any idea about it?

**Comment by rarazac** [comment]
Does the provided minimal example work for you? If so, i would suggest to adapt one of this [models](https://github.com/InES-HPMM/k2arm/blob/master/models.py) and retrain it. Be aware, not many layers types are supported.

**Comment by PriceWang** [comment]
The example models are available. Thanks.
