### ISSUE TITLE
Error generating Generating CMSIS Code 

### ISSUE THREAD

**Issue by syousufimam** [InES-HPMM/k2arm#3]
I have used tflite & keras to train and generate a model. I'm using the same model to generate the CMSIS NN c code that goes with it. I made the necessary changes to the function and ran the example above. When I run, I get the following error.

File "k2arm.py", line 295, in getDenseLayersInformation
    for layer in self.model.layers:
AttributeError: 'str' object has no attribute 'layers'

**Comment by rarazac** [comment]
Could you provide your model arch? Can you translate convert the example models?

**Comment by syousufimam** [comment]
![image](https://user-images.githubusercontent.com/17435955/139814842-1901c844-749f-4854-b12c-ee2bf8133752.png)
My model is in .h5/.tflite format , and I have tried both. I get the same error. 
I did not try the example models.

**Comment by rarazac** [comment]
Does the [example script](https://github.com/InES-HPMM/k2arm/blob/master/ARM/host/generateCMSISCode.py) work?
The script uses similar [models](https://github.com/InES-HPMM/k2arm/blob/master/models.py), generated with this [script](https://github.com/InES-HPMM/k2arm/blob/master/ARM/host/k2arm.py).

Please try the example models and report back if those work for you

**Comment by syousufimam** [comment]
Yes the example model works fine for me with just one edit as follows- 
In k2arm.py line 312 - tf.compat.v1.fake_quant_with_min_max_vars

Also I cannot access the links (https://github.zhaw.ch/login?return_to=https%3A%2F%2Fgithub.zhaw.ch%2Fhpmm%2Fk2arm%2Fblob%2Fmaster%2Fmodels.py) -
 it asks for Github enterprise credentials.
![image](https://user-images.githubusercontent.com/17435955/140088718-6bcee30b-3b69-4be1-8999-9b874dcc61f3.png)

**Comment by rarazac** [comment]
Ups sorry I had the wrong link (changed them in the original comment)

If the example models/script work for you I suggest that you start with them and change them to your own model

**Comment by syousufimam** [comment]
Thanks Rarazac- 
I have used the example code and edited accordingly.
I get the following error -
![image](https://user-images.githubusercontent.com/17435955/140104076-fd9e93b6-0812-45de-870a-6d9d7bc834ba.png)

I have one more question: what will be the model's extension? Yes, I see **.Keras** appears in the example.
I have **.h5** and **.tflite** models and for **.keras** , I simply changed the extension in my script while generating the model, but I'm not sure if the generated model is correct. And I get the error shown above for all three models.

**Comment by rarazac** [comment]
This looks like an IO problem. Does the model file exist at the path you specified?
 I suggest to you that you just change the model architecture and training data in the [example script provided](https://github.com/InES-HPMM/k2arm/blob/master/models.py) according to your use case because they work for you!

Keep it mind that everything was tested with those versions:
   - ubnntu 18.04
   - python 3.6
   - tensorflow 1.10.0
   - keras version 2.2.4 
   - [STM32CubeMX](https://www.st.com/en/development-tools/stm32cubemx.html)
   - [X-Cube-AI](https://www.st.com/en/embedded-software/x-cube-ai.html)
   - arm-none-eabi-gcc 6.3.1

**Comment by rarazac** [comment]
Closing due to no response in 1 week

**Comment by syousufimam** [comment]
Sorry for the late update. The problem is still the same. I was using it on windows 10 with anaconda / spyder for running the same. But as you have  mentioned about the system requirement I will switch my project into a Linux system and update accordingly.

**Comment by syousufimam** [comment]
System - WIN10 - Anaconda / Spyder / Keras version 2.6.0 

I was trying with my own model , the architecture of the model is given in the above comments. 
I got this error in the k2arm.py .
![image](https://user-images.githubusercontent.com/17435955/154187646-46d697f4-9493-4586-80a4-e29039f9e5bc.png)

Am I missing something ?  Does a higher Keras version will cause this problem ?

**Comment by rarazac** [comment]
Does it work with the example models and keras 2.6.0? If so I would recommend to build on top of that. If the example models do not work I suggest that you use exact the same versions as described above!
